### ISSUE TITLE
403 when attempting to download TTREngine

### ISSUE THREAD

**Issue by asonix** [JonathanHelianthicusDoe/shticker_book_unwritten#2]
I recently tried launching ttr through shticker_book_unwritten after not playing for a while, and got an upgrade error for the most recent TTREngine. I tried deleting my existing TTR game files and re-running the launcher but I'm encountering the same error.

This happened on version 1.0.0 from crates.io, and version 1.0.2 that I compiled from this repository.

```
        Downloading TTREngine.1adbc1116a.bz2 [attempt 1/5]
        Bad status code after requesting download: 403 Forbidden, retrying...
```

I'm on elementary OS 5.1 (based on Ubuntu 18.04) with linux kernel 5.3 if that matters

**Comment by JonathanHelianthicusDoe** [comment]
Hey, thanks for filing an issue. I have a setup nearly identical to yours, and tried reproducing the same thing by selecting a fresh install directory to force a fresh re-download of the files, but just ended up with:

```
[ 2/22] Checking for updates for TTREngine
        Checking to see if file already exists...
        File doesn't exist, downloading from scratch...
        Downloading TTREngine.1adbc1116a.bz2 [attempt 1/5]
        Checking SHA1 hash of TTREngine.1adbc1116a.bz2
        SHA1 hash matches! Extracting...
        Checking SHA1 hash of extracted file...
        SHA1 hash matches!
        Deleting compressed version...
        TTREngine all done downloading!
```

And also &ldquo;manually&rdquo; downloading via `wget https://download.toontownrewritten.com/patches/TTREngine.1adbc1116a.bz2` works as well. Maybe your config file has a stale URI for the TTR CDN? The config file defaults to `"$XDG_CONFIG_HOME"/shticker_book_unwritten/config.json` and then, if `$XDG_CONFIG_HOME` is undefined (or the empty string), to `"$HOME"/.config/shticker_book_unwritten/config.json`. Also you can specify it in your `shticker_book_unwritten` invocation via the `-c`/`--config` flag, instead.

The current default CDN URI is `https://download.toontownrewritten.com/patches/`.

**Comment by asonix** [comment]
That did the trick! The CDN url in the config was outdated. I assumed the binary would have updated it, but that seems to not be the case.
