### ISSUE TITLE
Windows detach from batch file

### ISSUE THREAD

**Issue by dbz2k** [JonathanHelianthicusDoe/shticker_book_unwritten#4]
Hello, I am using batch file to auto login, and detach, but for some reason on windows the command prompt never closes on windows, and TTR client will close if the close the command prompt.

If I run the same command in inside command prompt without a batch file detach works. 

shticker_book_unwritten -u exampleaccount -d

**Comment by JonathanHelianthicusDoe** [comment]
So, the way that `-d` basically works here is by exiting the program (sbu) entirely once `login::login` has been called. This is just a normal exit; nothing special, no `std::process::abort`, no `std::process::exit`, just returning `Ok(())` from `main`, which should result in the process exiting normally with a successful error code (e\.g. `0`).

The only thing that I can think of that would be related is how `login::launch` actually does the game launching. It looks something like this:

```rust
    process::Command::new(&command_text)
        .current_dir(&config.install_dir)
        .env("TTR_PLAYCOOKIE", play_cookie)
        .env("TTR_GAMESERVER", game_server)
        .stdin(process::Stdio::null())
        .stdout(process::Stdio::null())
        .stderr(process::Stdio::null())
        .spawn()
        .map_err(Error::ThreadSpawnError)
```

This spawns a new “process” (see here: <https://doc.rust-lang.org/std/process/struct.Command.html>) and eliminates any connection of that process to a `stdin`, `stdout`, or `stderr` (other than connecting to `/dev/null` or similar). I don’t really know anything about Windows or how batch files work, but maybe this is useful information. It’s possible that you can configure your batch file (similar to e\.g. how you might use `set` in a bash script) to behave differently in the presence of orphaned processes, or even explicitly do something like:

```batch
shticker_book_unwritten -u exampleaccount -d
abort
```

I’m not really sure.
